### ISSUE TITLE
Publish our pipeline images to a public registry

### ISSUE THREAD

**Issue by Zerpet** [rabbitmq/cluster-operator#211]
At the moment our pipeline (private) pushes images to a private registry. We should publish our images to a public registry to ease the consumption of this project. We will try to create an account under `rabbitmq-operator` in DockerHub and publish there.

I'm planning on working this issue in a 2-step phase.

**Phase 1: Lift & Shift** -- keep our pipeline with minimal changes and just publish to DockerHub.

**Phase 2: Implement a new release strategy** -- will work on #190, make a proposal and implement the outcome.

- [x] Phase 1
  - [x] Create DockerHub account and necessary access tokens
  - [x] Change pipeline
- [ ] Phase 2
  - [x] Publish our "dev" images to a staging or dev repo
  - [x] Provide GIT_COMMIT arg in docker build job
  - [ ] Cleanup tags in "prod" repo or publish to a "prod" or "release" repo
  - [x] Write a proposal for release strategy

**Comment by Zerpet** [comment]
### Context 

Adapting the pipeline is proving a bit more challenging than initially expected. Our pipeline job that runs system tests is expecting the Operator image to be hosted in PivNet registry. This assumption is not true anymore and we have to make a few changes in the pipeline job to pull from DockerHub.

The not-so-straight-forward change is in the system tests themselves. We have a test case that pulls RabbitMQ image from PivNet registry because we want to test that we can pull from private registries. This test expects a Secret created by `Makefile` to authenticate to the private registry.

We have to make changes to the pipeline job so that it creates the registry Secret *and* sets the Operator image to DockerHub repository. An initial set of changes in the CI repo live in branch `publish-to-dockerhub`.

**Comment by Zerpet** [comment]
Phase 1 is complete after merging #220 and a small change to the system tests job in CI.

**Comment by Zerpet** [comment]
Blocked by #190
