### ISSUE TITLE
Upgrade to rabbitmq 3.8.3 and cut a new release on PivNet

### ISSUE THREAD

**Issue by ChunyiLyu** [rabbitmq/cluster-operator#48]
**Is your feature request related to a problem? Please describe.**
Bump to the latest and greatest rabbitmq to take advantage the incremental upgrade.

**Describe the solution you'd like**
Use the docker image of the latest version.

**Describe alternatives you've considered**
N/A

**Additional context**
Make sure to also change the version in our pipeline.

Michal found that version 0.8.0 (next) is using RabbitMQ 3.8.2. Let's investigate this and confirm if this is the case for 0.7.0.

### Tasks
- [x] Request OSL
- [x] Update docs to describe the potential side effects of `preStop` hook (infinite wait to terminate pods)
- [x] Update Norsk Config to scan images in our registry
- [x] Update Norsk Config to remove Service Broker scan roots
- [x] Confirm that 0.7.0-build.41 is using RabbitMQ 3.8.3.
